language: java
sudo: false # faster builds

jdk:
  - openjdk8
  - openjdk11
script:
  - travis_wait 30 mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

